### ISSUE TITLE
计算出来的有些有问题

### ISSUE THREAD

**Issue by 721916348** [sp0re/easy-calc#3]
1.负数计算有问题
const obj2 = {
  budgetaryPlanning: 1,
  budgetaryPlanningDetailMoney: 1,
  increaseAmount: 2,
  good: -1,
  good2: 2
}
const result = calc( 'good+good2', {
  variable: obj2,
})
console.log( result ) // 【结果等于 -13】

2.计算的对象中属性重复的时候，会报错
const obj2 = {
  budgetaryPlanning: -1,
  budgetaryPlanningDetailMoney : 1,
  increaseAmount: 2,
  good: -1,
  good2: 2
}
const result = calc( 'budgetaryPlanningDetailMoney+increaseAmount', {
  variable: obj2,
})
console.log( result ) // 【Uncaught (in promise) Error: [big.js] Invalid number】

**Comment by 721916348** [comment]
求求大佬修复，项目没办法干下去了

**Comment by sp0re** [comment]
抱歉，这个问题是正则不够严谨导致的，已修复，见版本1.1.1
